"""Public Research V1 contracts, adapters, aggregation, and output helpers."""

from .aggregation import PriceAggregation, aggregate_price_results
from .bom_ai import (
    BomAiAdapter,
    BomAiBrowserConfig,
    BomAiCapture,
    BomAiClientError,
    BomAiCredentialedClient,
    BomAiCredentialProvider,
    BomAiLogin,
    BomAiPriceRecord,
    BomAiRawPage,
    PlaywrightBomAiAuthenticatedBrowser,
    calendar_month_cutoff,
)
from .contracts import ResearchInput, ResearchReasonCode, ResearchResult, ResearchStatus
from .credentials import (
    RESEARCH_CREDENTIAL_SITE_IDS,
    BomAiCoreCredentialProvider,
    CoreLoginBridge,
    CoreResearchCredentials,
    CredentialReadiness,
    IcNetCoreLoginProvider,
    InsoCoreCredentialProvider,
)
from .ecb_fx import EcbDailyUsdRmbProvider, EcbFxError
from .excel_output import (
    ExcelConsistencyError,
    ExcelOutputError,
    ExcelWriteError,
    ResearchExcelOutput,
)
from .findchips import FindchipsAdapter, FindchipsHttpClient
from .fx import UsdRmbProvider, UsdRmbQuote
from .hqew import CdpHqewClient, HqewAdapter
from .icnet import (
    BrandResolution,
    CdpIcNetClient,
    IcNetAdapter,
    IcNetLogin,
    IcNetPage,
    IcNetPageUnavailable,
    IcNetParseError,
    IcNetResult,
    IcNetRow,
    classify_stock,
    extract_manufacturer_display,
    parse_icnet_rows,
    select_brand_by_frequency,
    sum_certified_stock,
)
from .inso_history import (
    InsoBrowserConfig,
    InsoCredentialedClient,
    InsoCredentialProvider,
    InsoHistoryAdapter,
    InsoHistoryCapture,
    InsoHistoryRecord,
    InsoLogin,
    InsoReadError,
    InsoReadOnlyBrowser,
    PlaywrightInsoReadOnlyBrowser,
)
from .lcsc import LcscAdapter, LcscBrowserClient, LcscHttpClient
from .runtime import (
    BrowserRuntimeConfig,
    CdpRuntimeConfig,
    IcNetRuntimeConfig,
    ResearchRuntimeConfig,
    ResearchRuntimeConfigError,
    ResearchRuntimeError,
    ResearchRuntimePrerequisiteError,
    ResearchRuntimeReadiness,
    assess_readiness,
    build_icnet_client,
    build_production_research_service,
    build_research_service,
    default_runtime_config_path,
    format_readiness,
    load_runtime_config,
    probe_loopback_endpoint,
    require_ready,
)
from .service import ResearchExecution, ResearchService

__all__ = [
    "RESEARCH_CREDENTIAL_SITE_IDS",
    "BomAiAdapter",
    "BomAiBrowserConfig",
    "BomAiCapture",
    "BomAiClientError",
    "BomAiCoreCredentialProvider",
    "BomAiCredentialProvider",
    "BomAiCredentialedClient",
    "BomAiLogin",
    "BomAiPriceRecord",
    "BomAiRawPage",
    "BrandResolution",
    "BrowserRuntimeConfig",
    "CdpHqewClient",
    "CdpIcNetClient",
    "CdpRuntimeConfig",
    "CoreLoginBridge",
    "CoreResearchCredentials",
    "CredentialReadiness",
    "EcbDailyUsdRmbProvider",
    "EcbFxError",
    "ExcelConsistencyError",
    "ExcelOutputError",
    "ExcelWriteError",
    "FindchipsAdapter",
    "FindchipsHttpClient",
    "HqewAdapter",
    "IcNetAdapter",
    "IcNetCoreLoginProvider",
    "IcNetLogin",
    "IcNetPage",
    "IcNetPageUnavailable",
    "IcNetParseError",
    "IcNetResult",
    "IcNetRow",
    "IcNetRuntimeConfig",
    "InsoBrowserConfig",
    "InsoCoreCredentialProvider",
    "InsoCredentialProvider",
    "InsoCredentialedClient",
    "InsoHistoryAdapter",
    "InsoHistoryCapture",
    "InsoHistoryRecord",
    "InsoLogin",
    "InsoReadError",
    "InsoReadOnlyBrowser",
    "LcscAdapter",
    "LcscBrowserClient",
    "LcscHttpClient",
    "PlaywrightBomAiAuthenticatedBrowser",
    "PlaywrightInsoReadOnlyBrowser",
    "PriceAggregation",
    "ResearchExcelOutput",
    "ResearchExecution",
    "ResearchInput",
    "ResearchReasonCode",
    "ResearchResult",
    "ResearchRuntimeConfig",
    "ResearchRuntimeConfigError",
    "ResearchRuntimeError",
    "ResearchRuntimePrerequisiteError",
    "ResearchRuntimeReadiness",
    "ResearchService",
    "ResearchStatus",
    "UsdRmbProvider",
    "UsdRmbQuote",
    "aggregate_price_results",
    "assess_readiness",
    "build_icnet_client",
    "build_production_research_service",
    "build_research_service",
    "calendar_month_cutoff",
    "classify_stock",
    "default_runtime_config_path",
    "extract_manufacturer_display",
    "format_readiness",
    "load_runtime_config",
    "parse_icnet_rows",
    "probe_loopback_endpoint",
    "require_ready",
    "select_brand_by_frequency",
    "sum_certified_stock",
]
