"""Public Research V1 contracts, adapters, aggregation, and output helpers."""

from .aggregation import PriceAggregation, aggregate_price_results
from .bom_ai import (
    BomAiAdapter,
    BomAiCapture,
    BomAiClientError,
    BomAiCredentialedClient,
    BomAiCredentialProvider,
    BomAiLogin,
    BomAiPriceRecord,
    BomAiRawPage,
    calendar_month_cutoff,
)
from .contracts import ResearchInput, ResearchReasonCode, ResearchResult, ResearchStatus
from .ecb_fx import EcbDailyUsdRmbProvider, EcbFxError
from .excel_output import (
    ExcelConsistencyError,
    ExcelOutputError,
    ExcelWriteError,
    ResearchExcelOutput,
)
from .findchips import FindchipsAdapter, FindchipsHttpClient
from .fx import UsdRmbProvider, UsdRmbQuote
from .hqew import CdpHqewClient, HqewAdapter
from .icnet import (
    BrandResolution,
    CdpIcNetClient,
    IcNetAdapter,
    IcNetLogin,
    IcNetPage,
    IcNetPageUnavailable,
    IcNetParseError,
    IcNetResult,
    IcNetRow,
    classify_stock,
    extract_manufacturer_display,
    parse_icnet_rows,
    select_brand_by_frequency,
    sum_certified_stock,
)
from .inso_history import (
    InsoBrowserConfig,
    InsoCredentialedClient,
    InsoCredentialProvider,
    InsoHistoryAdapter,
    InsoHistoryCapture,
    InsoHistoryRecord,
    InsoLogin,
    InsoReadError,
    InsoReadOnlyBrowser,
    PlaywrightInsoReadOnlyBrowser,
)
from .lcsc import LcscAdapter, LcscBrowserClient, LcscHttpClient
from .service import ResearchExecution, ResearchService

__all__ = [
    "BomAiAdapter",
    "BomAiCapture",
    "BomAiClientError",
    "BomAiCredentialProvider",
    "BomAiCredentialedClient",
    "BomAiLogin",
    "BomAiPriceRecord",
    "BomAiRawPage",
    "BrandResolution",
    "CdpHqewClient",
    "CdpIcNetClient",
    "EcbDailyUsdRmbProvider",
    "EcbFxError",
    "ExcelConsistencyError",
    "ExcelOutputError",
    "ExcelWriteError",
    "FindchipsAdapter",
    "FindchipsHttpClient",
    "HqewAdapter",
    "IcNetAdapter",
    "IcNetLogin",
    "IcNetPage",
    "IcNetPageUnavailable",
    "IcNetParseError",
    "IcNetResult",
    "IcNetRow",
    "InsoBrowserConfig",
    "InsoCredentialProvider",
    "InsoCredentialedClient",
    "InsoHistoryAdapter",
    "InsoHistoryCapture",
    "InsoHistoryRecord",
    "InsoLogin",
    "InsoReadError",
    "InsoReadOnlyBrowser",
    "LcscAdapter",
    "LcscBrowserClient",
    "LcscHttpClient",
    "PlaywrightInsoReadOnlyBrowser",
    "PriceAggregation",
    "ResearchExcelOutput",
    "ResearchExecution",
    "ResearchInput",
    "ResearchReasonCode",
    "ResearchResult",
    "ResearchService",
    "ResearchStatus",
    "UsdRmbProvider",
    "UsdRmbQuote",
    "aggregate_price_results",
    "calendar_month_cutoff",
    "classify_stock",
    "extract_manufacturer_display",
    "parse_icnet_rows",
    "select_brand_by_frequency",
    "sum_certified_stock",
]
